version: 3.0.{build}
skip_tags: true
image: Visual Studio 2019
environment:
  access_token:
    secure: Eq6BjtZ80BXKLwFMg76IjuQAvbLjbojIF/X/ARouGVhxPneJtgDfCXMPNgJ7KBKq
  sonar_token:
    secure: W7pHKhuTW6Lh8WlXJNTOIaOzeuxLi+H6Nqmnm4pr28jM6jyIpOZ+1r10lIQi0eCA
  JAVA_HOME: C:\Program Files\Java\jdk14
nuget:
  disable_publish_on_pr: true
build_script:
  - dotnet --info
  - dotnet restore
  - dotnet build -c Release
  - dotnet publish SyncChanges.Console -c Release -f net5.0
  - dotnet publish SyncChanges.Service -c Release -f net461
  - dotnet pack --include-symbols --include-source -c Release SyncChanges
  - dotnet pack --include-symbols --include-source -c Release SyncChanges.Console
  - dotnet pack --include-symbols --include-source -c Release SyncChanges.Service
  - 7z a -mx=9 SyncChanges.Console.%APPVEYOR_BUILD_VERSION%.zip ".\SyncChanges.Console\bin\Release\net5.0\publish\*"
  - 7z a -mx=9 SyncChanges.Service.%APPVEYOR_BUILD_VERSION%.zip ".\SyncChanges.Service\bin\Release\net461\publish\*"
test_script:
  - ps: |
      if (-not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
          dotnet tool install --global dotnet-sonarscanner
          dotnet sonarscanner begin /k:"mganss_SyncChanges" /v:$env:APPVEYOR_BUILD_VERSION /o:"mganss-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$env:sonar_token" /d:sonar.cs.opencover.reportsPaths="$($env:APPVEYOR_BUILD_FOLDER)\coverage.xml" /d:sonar.exclusions="**/*.xsd" /d:sonar.coverage.exclusions="**/Program.cs"
          dotnet build
      }
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput="..\coverage.xml" SyncChanges.Tests\SyncChanges.Tests.csproj /p:Include="[SyncChanges]*"
  - ps: |
      if (-not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
          dotnet sonarscanner end /d:sonar.login="$env:sonar_token"
      }
  - pip install codecov
  - codecov -f "coverage.xml"
artifacts:
  - path: 'SyncChanges\**\*.*nupkg'
  - path: 'SyncChanges.Console\**\*.*nupkg'
  - path: 'SyncChanges.Service\**\*.*nupkg'
  - path: SyncChanges.Console.%APPVEYOR_BUILD_VERSION%.zip
  - path: SyncChanges.Service.%APPVEYOR_BUILD_VERSION%.zip
deploy:
  - provider: GitHub
    tag: v$(APPVEYOR_BUILD_VERSION)
    release: $(APPVEYOR_BUILD_VERSION)
    description: '$(APPVEYOR_REPO_COMMIT_MESSAGE)'
    auth_token:
      secure: Eq6BjtZ80BXKLwFMg76IjuQAvbLjbojIF/X/ARouGVhxPneJtgDfCXMPNgJ7KBKq
    artifact: /SyncChanges\..*\.zip/
    draft: true
    on:
      branch: master
